### ISSUE TITLE
生成视频报错

### ISSUE THREAD

**Issue by xiamulo** [qihao123/GenVIdeo#1]
![image](https://user-images.githubusercontent.com/47745636/77386292-71981a80-6dc5-11ea-9c4a-8ccd7c09e99d.png)

**Comment by xiamulo** [comment]
magick.exe: no images for write '-write' 'PNG32:C:\Users\user\AppData\Local\Temp\tmppvij55k6.png' at CLI arg 18 @ error/operation.c/CLINoImageOperator/4850.

**Comment by qihao123** [comment]
调用moviepy需要安装一个叫imagemagic的程序，在imagemagic文件夹你安装一下

**Comment by qihao123** [comment]
moviepy安装还需要配置一些东西，你最好百度或者谷歌一下

**Comment by qihao123** [comment]
项目刚开始效果不是很理想，可以先点个start过一段时间再来玩

**Comment by xiamulo** [comment]
已经可以了，效果不太好，中文字幕加上去会变成数字

**Comment by qihao123** [comment]
中文编码问题

**Comment by xiamulo** [comment]
能解决吗，中文编码问题

**Comment by qihao123** [comment]
已经解决了，还有些其他问题我还要再改改
